# Generated by Django 3.1.7 on 2021-02-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210228_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='camps',
        ),
    ]
